before_script:
    - /usr/bin/pipenv install
    # Pin setuptools
    - /usr/bin/pipenv install setuptools==42.0.2
    - echo -e "[buildout]\nlogin = admin\npassword = admin" > secret.cfg
    - ln -fs local_ci.cfg local.cfg
    - ./bin/develop up -f || true
    - /usr/bin/pipenv run buildout -t 3 || /usr/bin/pipenv run buildout -v

test:
  script:
     - export DISPLAY=:99
     - /usr/bin/pipenv run pre-commit run -a
     - ./bin/test
