repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python 3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
        additional_dependencies:
          - flake8-debugger
          - flake8-print
          - flake8-deprecated
          - flake8-plone-hasattr
          - flake8-plone-api
          - pep8-naming
          - flake8-mutable
          - flake8-tidy-imports
      - id: debug-statements
      - id: fix-encoding-pragma
      - id: check-xml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: double-quote-string-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
